behaviors:
  RVOLabel:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 204800
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: False
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 20000
environment_parameters:
  rew_x: -0.0005
  rew_z: -0.0005
  moveSmooth: 0.001
  xzDistThres: 1.5
  moveUnit: 3
  num_agents:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: RVOLabel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.25
        value: 4.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: RVOLabel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 8.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: RVOLabel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 12.0
      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: RVOLabel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 16.0
      - name: Lesson4
        value: 20.0